### ISSUE TITLE
Segmentation Faults

### ISSUE THREAD

**Issue by subins2000** [OpenWebTorrent/openwebtorrent-tracker#10]
At times, segemntation faults are happening for reasons idk. Would like to know how stable is OWT ? I'm now thinking of making a Java port of WebTorrent tracker.

**Comment by alxhotel** [comment]
Hi @subins2000,

Yeah, the current version is not very stable. But I believe it just needs a few tweaks to fix it

I'll try to fix it this week. But if you find a fix sooner, please send a PR :)

**Comment by subins2000** [comment]
I ended up porting OTT to Java :sweat_smile: it works : https://github.com/subins2000/webtorrent-tracker-java/

**Comment by alxhotel** [comment]
I think this problem should be fixed by now.

Please reopen if you keep seen this error.
