### ISSUE TITLE
Error: Cert and key must exists

### ISSUE THREAD

**Issue by ZenDarkmaster** [OpenWebTorrent/openwebtorrent-tracker#11]
Hello,

Can you please tell me what am I doing wrong?

![image](https://user-images.githubusercontent.com/34407163/102690647-6e896800-4239-11eb-940c-76a55793a53a.png)

```
tr@srv1:~/openwebtorrent-tracker$ ls
build  certificate.pem  cmake  CMakeLists.txt  deps  key.pem  Makefile  README.md  src  tests
tr@srv1:~/openwebtorrent-tracker$ ./build/openwebtorrent-tracker --port 8000 --ssl-cert /home/tr/openwebtorrent-tracker/certificate.pem --ssl-key /home/tr/openwebtorrent-tracker/key.pem
Error: Cert and key must exists
```

**Comment by ZenDarkmaster** [comment]
The certificates exist in the directory, I double-checked everything 7 times, all attempts with other certificates are also unsuccessful.
More detailed information may be needed? If so, tell me which one.

**Comment by alxhotel** [comment]
The CLI options weren't implemented yet.

I just pushed a new commit with the changes. Pull the new changes and let me know if it works.

**Comment by ZenDarkmaster** [comment]
> The CLI options weren't implemented yet.
> 
> I just pushed a new commit with the changes. Pull the new changes and let me know if it works.

Hello, Alex!

It didn't work out yet, I marked the key points in the screenshots.
Complete installation log in attachment.
![Screenshot_1](https://user-images.githubusercontent.com/34407163/102717724-b0d4a700-4316-11eb-9eec-c7fd929e21c9.png)
![Screenshot_2](https://user-images.githubusercontent.com/34407163/102717731-b7631e80-4316-11eb-876c-e33e40ca0f46.png)
[install.log](https://github.com/OpenWebTorrent/openwebtorrent-tracker/files/5721134/install.log)

**Comment by alxhotel** [comment]
Oops, sorry. I missed typed something.

Please, try again :)
