### ISSUE TITLE
Can't setup submodules

### ISSUE THREAD

**Issue by subins2000** [OpenWebTorrent/openwebtorrent-tracker#7]
Hi !

First of all, thanks for making this <3

I tried setting it up, but submodule init is failing :

```
$ git submodule update --init --depth 1
Cloning into '/home/mint/Other/Projects/GitHub/openwebtorrent-tracker/deps/json'...
Cloning into '/home/mint/Other/Projects/GitHub/openwebtorrent-tracker/deps/uWebSockets'...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: remote error: upload-pack: not our ref d39fb24c22367db2949d3cb441cb979072491e35
Fetched in submodule path 'deps/json', but it did not contain d39fb24c22367db2949d3cb441cb979072491e35. Direct fetching of that commit failed.
```

**Comment by subins2000** [comment]
git version is 2.26.2 (Ubuntu 18.04)

Yes, I did try `git submodule update --init --recursive`. I got it working now, by doing a `git fetch --depth 1 origin tag v3.9.1 && git checkout v3.9.1` in `deps/json`.

Will updating git help ?

**Comment by subins2000** [comment]
Also clicking json folder in deps on GitHub tree viewer is 404ing : https://github.com/nlohmann/json/tree/d39fb24c22367db2949d3cb441cb979072491e35

**Comment by alxhotel** [comment]
Ah you are right.

I just updated the git submodule. It should be fixed now.
